const Actions = {
  SIGNUP: "SIGNUP",
  SIGNIN: "SIGNIN",
  SIGNOUT: "SIGNOUT",
  RESETPASSWORD: "RESETPASSWORD",

  ADDSONG: "ADDSONG",
  DELETESONG: "DELETESONG",
  EDITSONG: "EDITSONG",
  LOADSONGS: "LOADSONGS",
  MYSONGS: "MYSONGS",
};

export default Actions;